export const students = [
    {
      id: 1,
      name: "Shaj",
      ticketNumber: "12345",
      ticketTopic: 5.0,
      examGrade: 4.5,
      ratingGrade: 3.7,
      status: "P",
      comments: "Good progress, needs improvement in coding style.",
    },
    {
      id: 2,
      name: "Ram",
      ticketNumber: "45894",
      ticketTopic: 5.0,
      examGrade: 4.0,
      ratingGrade: 3.9,
      status: "P",
      comments: "Good progress, needs improvement in coding style.",
    },
    {
      id: 3,
      name: "Gopal",
      ticketNumber: "49895",
      ticketTopic: 5.0,
      examGrade: 4.2,
      ratingGrade: 4.0,
      status: "P",
      comments: "Good progress, needs improvement in coding style.",
    },
    {
      id: 4,
      name: "Hyndavi",
      ticketNumber: "46287",
      ticketTopic: 5.0,
      examGrade: 4.5,
      ratingGrade: 3.5,
      status: "P",
      comments: "Good progress, needs improvement in coding style.",
    },
    {
      id: 5,
      name: "Sai",
      ticketNumber: "32895",
      ticketTopic: 5.0,
      examGrade: 4.7,
      ratingGrade: 3.2,
      status: "P",
      comments: "Good progress, needs improvement in coding style.",
    },
    {
      id: 6,
      name: "Yasawi",
      ticketNumber: "96347",
      ticketTopic: 5.0,
      examGrade: 4.5,
      ratingGrade: 3.7,
      status: "P",
      comments: "Good progress, needs improvement in coding style.",
    },
    // Add more student entries here
  ];
  